networks:
  ticket_network:
    driver: bridge
services:
  db-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_ticket
    networks:
      - ticket_network
    restart: unless-stopped
    volumes:
      - ./src/main/resources/data:/docker-entrypoint-initdb.d
  react-app:
    image: findmeticket/react-app
    ports:
      - "81:8079"
    networks:
      - ticket_network
    env_file:
      - frontend/.env.docker
  spring-boot-app:
    image: findmeticket/spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - src/main/resources/.env.docker
    networks:
      - ticket_network
    depends_on:
      - db-postgres
  selenium-hub:
    image: selenium/hub:4.2
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - ticket_network
  driver-chrome:
    image: selenium/node-chrome:4.2
    ports:
      - "6900:5900"
    scale: 7
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - ticket_network