spring:
  ##-------------------------
  ## JPA
  ##-------------------------
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA}
  web:
    resources:
      add-mappings: false

  ##-------------------------
  ## Mail sender configuration
  ##-------------------------
  mail:
    host: smtp.gmail.com
    port: '587'
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ##-------------------------
  ## Database configuration
  ##-------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ticket?currentSchema=${DATABASE_SCHEMA}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    schema: ${DATABASE_SCHEMA}

  ##-------------------------
  ## Liquibase configuration
  ##-------------------------
  liquibase:
    change-log: classpath:/liquibase/master.yaml
    default-schema: ${DATABASE_SCHEMA}

##-------------------------
## Spring documentation
##-------------------------
springdoc:
  enable-kotlin: false

##-------------------------
## Endpoints management
##-------------------------
management:
  endpoints:
    web:
      exposure:
        include: '*'

#-------------------------
# Encoding
#-------------------------
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    include-message: always

##-------------------------
## Logging level
##-------------------------
logging:
  level:
    liquibase: DEBUG
    ROOT: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        web: DEBUG
        security: TRACE
      hibernate: ERROR

##-------------------------
## JWT Properties
##-------------------------
security:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationMin: '1440'
    refreshTokenExpirationMin: '43200'

##-------------------------
## Language detection file-configurations
##-------------------------
languages:
  files:
    profiles: eng.txt, ua.txt

#-------------------------
# Third-party ticket's services
#-------------------------
ticket:
  source:
    uri:
      busfor-ua-bus: 'https://busfor.ua/автобуси/%s/%s?on=%s&passengers=1&search=true'
      busfor-eng-bus: 'https://busfor.pl/buses/%s/%s?on=%s&passengers=1&search=true'
      proizd-ua-bus: 'https://bus.proizd.ua/'
      proizd-eng-bus: 'https://bus.proizd.ua/en'
      infobus-ua-bus: 'https://infobus.eu/ua/bus'
      infobus-eng-bus: 'https://infobus.eu/en/bus'
      infobus-eng-train: 'https://infobus.eu/en/train'
      infobus-ua-train: 'https://infobus.eu/ua/train'
      proizd-eng-train: 'https://proizd.ua/en'
      proizd-ua-train: 'https://proizd.ua/'

#-------------------------
# API keys
#-------------------------
api:
  key:
    currency-rate: ${CURRENCY_API_KEY}
    google-client-id: ${GOOGLE_AUTH_KEY}

webdriver:
  selenium:
    url: 'http://selenium-hub:4444'